package main

import (
	"context"
	"fmt"
	"log"
	"time"

	"github.com/chromedp/chromedp"
)

func main() {
	// 1. Point to the remote debugging port of your already-logged-in browser
	devtoolsURL := "ws://127.0.0.1:9222"

	allocCtx, cancelAlloc := chromedp.NewRemoteAllocator(context.Background(), devtoolsURL)
	defer cancelAlloc()

	// 2. Create the context (this connects to the running Chrome instance instead of spinning up a new one)
	ctx, cancelCtx := chromedp.NewContext(allocCtx)
	defer cancelCtx()

	// Add a timeout just in case elements take too long to appear
	ctx, cancelTimeout := context.WithTimeout(ctx, 30*time.Second)
	defer cancelTimeout()

	// 3. Execute the automation steps
	var resultHTML string
	err := chromedp.Run(ctx,
		// Navigate to your application page (relying on existing cookies)
		chromedp.Navigate("http://localhost:8080/app"), // Adjust to your actual URL

		// Wait for the app to load by verifying the sidebar search button exists
		chromedp.WaitVisible(`#sidebarSearch`, chromedp.ByID),

		// Click the Search option in the sidebar
		chromedp.Click(`#sidebarSearch`, chromedp.ByID),

		// Since the search input isn't in the static HTML, it's likely generated by renderer.js.
		// We wait for the input element to be injected into the DOM dynamically.
		// (Adjust the selector below if the input has a specific class or ID like #searchInput)
		chromedp.WaitVisible(`#matchBox input, #mainSection input`, chromedp.ByQuery),

		// Type the search query into the newly rendered input box
		chromedp.SendKeys(`#matchBox input, #mainSection input`, "malware indicator", chromedp.ByQuery),

		// If there's a submit button, we click it. If it updates on type, we sleep briefly.
		// Let's simulate pressing 'Enter' to execute the search
		chromedp.SendKeys(`#matchBox input, #mainSection input`, "\n", chromedp.ByQuery),

		// Wait for results to populate inside the match box container
		chromedp.WaitVisible(`#matchBox .search-result, #matchBox div`, chromedp.ByQuery),

		// Grab the inner HTML of the match container to extract our data
		chromedp.InnerHTML(`#matchBox`, &resultHTML, chromedp.ByID),
	)

	if err != nil {
		log.Fatalf("Automation failed: %v", err)
	}

	fmt.Println("Successfully performed search! Current MatchBox Content:")
	fmt.Println(resultHTML)
}
